### ISSUE TITLE
Communication channel for developers

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/community#6]
We need to setup some channel for contributing developers.
Options:
- IRC
- [gitter](https://gitter.im)
- ...

Ideas are welcome.

**Comment by andyceo** [comment]
+1 for IRC.

To keep up with the times, Telegram is also nice choice

**Comment by robkorn** [comment]
I'm pretty open with any option, I would just like to mention that it may be of benefit if we don't create too many unique communication channels, as it may end up being hard for a new user to find where they need to go (or I suppose we just need a good page on ergoplatform.org that allows for people to easily get where they need to)

**Comment by aslesarenko** [comment]
[Discord](https://discord.gg/kj7s7nb) seems to work well for this.
